### ISSUE TITLE
Exception: KBeaconService has leaked IntentReceiver

### ISSUE THREAD

**Issue by pravingws** [kkmhogen/KBeaconProDemo_Android#12]
Getting this error in KBeaconsMgr.java library class file :

 **mBeaconMgr = KBeaconsMgr.sharedBeaconManager(this)**

```
04:33:20.155 ActivityThread           E  Service com.wrkspot.employee.widget.bluetooth.KBeaconService has leaked IntentReceiver com.kkmcn.kbeaconlib2.KBeaconsMgr$1@c9f3397 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                         android.app.IntentReceiverLeaked: Service com.wrkspot.employee.widget.bluetooth.KBeaconService has leaked IntentReceiver com.kkmcn.kbeaconlib2.KBeaconsMgr$1@c9f3397 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                         	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1875)
                                         	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1594)
                                         	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1827)
                                         	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
                                         	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
                                         	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:743)
                                         	at com.kkmcn.kbeaconlib2.KBeaconsMgr.initialize(KBeaconsMgr.java:148)
                                         	at com.kkmcn.kbeaconlib2.KBeaconsMgr.sharedBeaconManager(KBeaconsMgr.java:103)
                                         	at com.wrkspot.employee.widget.bluetooth.KBeaconService.onCreate(KBeaconService.kt:117)
                                         	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4940)
                                         	at android.app.ActivityThread.access$1800(ActivityThread.java:310)
                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                         	at android.os.Looper.loopOnce(Looper.java:226)
                                         	at android.os.Looper.loop(Looper.java:313)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by kkmhogen** [comment]
KBeaconsMgr is a global static variable that typically accompanies the entire lifecycle of an application. If you need to manually release the resource, please call KBeaconsMgr. clairBeaconManage() to do unregisterReceiver
